name: Go Checks

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    paths:
      - 'go.sum'
      - 'go.mod'
      - '**.go'
      - .github/workflows/golang.yml
      - '.goreleaser.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.sum'
      - 'go.mod'

permissions:
  security-events: write
  actions: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  Snapshot:
    if: ${{ startsWith(github.ref, 'refs/tags/v') == false }}
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      #- name: Test
      #  run: make test

#      - name: Download AutoComplete file
#        run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/urfave/cli/v2.25.7/autocomplete/bash_autocomplete -OutFile bash_completion

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: --snapshot --clean --skip=publish,sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-exporter
          path: dist/*
